// This file was autogenerated by /usr/local/google-closure/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../tetris/src/hvdoo/tetris/Board.js', ['hvdoo.tetris.Board'], ['hvdoo.tetris.Piece', 'hvdoo.tetris.util']);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/Canvas.js', ['hvdoo.tetris.Canvas'], []);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/Piece.js', ['hvdoo.tetris.Piece'], ['hvdoo.tetris.constants']);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/Sprite.js', ['hvdoo.tetris.Sprite'], []);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/Step.js', ['hvdoo.tetris.Step'], []);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/constants.js', ['hvdoo.tetris.constants'], []);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/input.js', ['hvdoo.tetris.input'], []);
goog.addDependency('../../../../tetris/src/hvdoo/tetris/util.js', ['hvdoo.tetris.util'], ['hvdoo.tetris.Sprite', 'hvdoo.tetris.constants']);
